ARG DOCKER_TAG

FROM kromanetwork/geth:${DOCKER_TAG}

RUN apk update && apk add --no-cache ca-certificates tzdata bash su-exec aria2

RUN mkdir -p /var/lib/kroma-geth/ee-secret && chmod -R 700 /var/lib/kroma-geth \
    && chmod 777 /var/lib/kroma-geth/ee-secret

# Cannot assume buildkit, hence no chmod
COPY ./docker-entrypoint.sh /usr/local/bin/
# Belt and suspenders
RUN chmod -R 755 /usr/local/bin/*

ENTRYPOINT ["geth"]
